# Use node-modules linker for compatibility with native modules
nodeLinker: node-modules

# Enable frozen lockfile to ensure reproducible installs
enableImmutableInstalls: true

# Cache folder (optional, can help CI/CD)
cacheFolder: .yarn/cache

# Informational: supported architectures for native modules
supportedArchitectures:
  os:
    - current
    # - darwin
    - linux #AWS
    # - win32
  cpu:
    - current
    - x64  #AWS
    # - ia32
    # - arm64
  libc:
    - current
    - glibc  #AWS
    # - musl

# Package extensions: optional native binaries for cross-platform support
packageExtensions:
  sharp@*:
    peerDependenciesMeta:
      "@img/sharp-linux-x64":
        optional: true
      "@img/sharp-linux-arm64":
        optional: true
      "@img/sharp-darwin-x64":
        optional: true
      "@img/sharp-darwin-arm64":
        optional: true
      "@img/sharp-win32-x64":
        optional: true
      "@img/sharp-win32-ia32":
        optional: true

# Environment variables for native builds (set these in CI/CD or locally)
# These can force sharp to download prebuilt binaries
# sharp_binary_host: "https://github.com/lovell/sharp-libvips/releases/download/v8.16.0/"
