Resources:
  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${env:EXPRESS_S3_TEMP_BUCKET}
      LifecycleConfiguration:
        Rules:
          - Id: ExpireAfter1Day
            Status: Enabled
            ExpirationInDays: 1
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - ${env:EXPRESS_PUBLIC_FRONTEND_URL}
              - http://localhost:3000
            AllowedHeaders:
              - Authorization
              - Content-Type
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            ExposedHeaders:
              - ETag
              - x-amz-request-id
              - x-amz-id-2
            MaxAge: 3000

  RatingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Ratings
      AttributeDefinitions:
        - AttributeName: rating_id
          AttributeType: S
        - AttributeName: project_id
          AttributeType: S
      KeySchema:
        - AttributeName: rating_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ProjectIndex
          KeySchema:
            - AttributeName: project_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
