Resources:
  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${env:EXPRESS_S3_TEMP_BUCKET}
      LifecycleConfiguration:
        Rules:
          - Id: ExpireAfter1Day
            Status: Enabled
            ExpirationInDays: 1
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - ${env:EXPRESS_PUBLIC_FRONTEND_URL}
              - http://localhost:3000
            AllowedHeaders:
              - Authorization
              - Content-Type
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            ExposedHeaders:
              - ETag
              - x-amz-request-id
              - x-amz-id-2
            MaxAge: 3000

  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Projects
      AttributeDefinitions:
        - AttributeName: project_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: share_url
          AttributeType: S
      KeySchema:
        - AttributeName: project_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ProjectIndex # by user_id
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: ShareUrlIndex # by share_url
          KeySchema:
            - AttributeName: share_url
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  RatingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Ratings
      AttributeDefinitions:
        - AttributeName: rating_id
          AttributeType: S
        - AttributeName: project_id
          AttributeType: S
      KeySchema:
        - AttributeName: rating_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ProjectIndex
          KeySchema:
            - AttributeName: project_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # Signup Creation Queue + DLQ
  SignupQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: signup-creation-queue
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SignupDLQ.Arn
        maxReceiveCount: 3

  SignupDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: signup-creation-dlq

  # Cleanup Queue + DLQ
  CleanupQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: signup-cleanup-queue
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CleanupDLQ.Arn
        maxReceiveCount: 3

  CleanupDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: signup-cleanup-dlq

  CreateProjectQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: create-project-queue
